stages:
  - build
  - greenlight
  - scan
 
build_job:
  image: maven:3.6.0-jdk-8
  stage: build
  before_script:
    - echo $CI_JOB_ID
    - echo $CI_SERVER_HOST
    - echo $CI_REPOSITORY_URL
    - export CI_SERVER_HOST="gitlab"
  script:
    - mvn clean package
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_build
    paths:
      - target/
    expire_in: 1 week
  cache:
    paths:
      - target/
      - .m2/repository
    
  
greenlight_job:
  stage: greenlight
  image: openjdk:8-jre
  dependencies:
    - build_job
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}_build
    paths:
      - results.json
      - results.txt
    expire_in: 1 week
    when: always
  script:
    - curl -O https://downloads.veracode.com/securityscan/gl-scanner-java-LATEST.zip
    - unzip gl-scanner-java-LATEST.zip gl-scanner-java.jar
    - java -jar gl-scanner-java.jar
      --api_id ${VERACODE_API_ID}
      --api_secret_key ${VERACODE_API_KEY}
      --build_dir "target/classes/"
      --source-dir "src/main/java/"
      --issue_details=true
      --summary_output=true

veracode-policy-scan:
    stage: scan
    image: openjdk:10
    only:
        - schedules
        - master
    before_script:
        - wget -q -O veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VERACODE_WRAPPER_VERSION}/vosp-api-wrappers-java-${VERACODE_WRAPPER_VERSION}.jar
    script:
        - java -jar --add-modules java.se.ee veracode-wrapper.jar -vid ${VERACODE_API_ID} -vkey ${VERACODE_API_KEY}
          -action UploadAndScan -appname "${CI_PROJECT_NAME}" -createprofile true -autoscan true
          -filepath target/verademo.war -version "job ${CI_JOB_ID} in pipeline ${CI_PIPELINE_ID}"