# Starter pipeline
- task: Veracode Flaw Importer@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'Veracode SaaS Platform'
    veracodeAppProfile: 
    sandboxName: 
    importType: 'All Flaws'
    workItemType: 'Bug'
    area: '$(system.teamProject)'
    addCweAsATag: false
    foundInBuild: false
    flawImportLimit: '1000'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
